language: python
os: linux
python: 3.7
env:
 - TOX_ENV=py37
 - TOX_ENV=docs
install:
 - pip install tox
script:
 - tox -e $TOX_ENV
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master